# Form implementation generated from reading ui file '/Users/byb/Downloads/qt_zuoye/my_realy_qt_my_ai_nb_副本/helpdialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpDialog(object):
    def setupUi(self, HelpDialog):
        HelpDialog.setObjectName("HelpDialog")
        HelpDialog.resize(420, 320)
        self.label = QtWidgets.QLabel(parent=HelpDialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 380, 200))
        self.label.setObjectName("label")
        self.btn_surprise = QtWidgets.QPushButton(parent=HelpDialog)
        self.btn_surprise.setGeometry(QtCore.QRect(20, 260, 56, 18))
        self.btn_surprise.setObjectName("btn_surprise")

        self.retranslateUi(HelpDialog)
        QtCore.QMetaObject.connectSlotsByName(HelpDialog)

    def retranslateUi(self, HelpDialog):
        _translate = QtCore.QCoreApplication.translate
        HelpDialog.setWindowTitle(_translate("HelpDialog", "游戏帮助"))
        self.label.setText(_translate("HelpDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">默认键位设置</span></p><p><span style=\" font-size:11pt;\">玩家1：A/D移动，W跳跃，S下穿平台，T射击，Y炸弹</span></p><p><span style=\" font-size:11pt;\">玩家2：←/→移动，↑跳跃，↓下穿平台，逗号射击，句号炸弹</span></p><p><span style=\" font-size:11pt;\">暂停键P | 允许二段跳 | 8发子弹自动换弹</span></p><p><span style=\" font-size:11pt;\">关闭窗口 Alt+F4</span></p></body></html>"))
        self.btn_surprise.setText(_translate("HelpDialog", "惊喜！"))
